#!/usr/bin/bash

# Taken and adapted from: https://git.zx2c4.com/password-store/tree/contrib/dmenu/passmenu

shopt -s nullglob globstar

otp=0
prompt="Password: "
copy=0

if [[ $1 == "-c" ]]; then
	copy=1
	shift
fi

if [[ $1 == "otp" ]]; then
	otp=1
	prompt="OTP: "
	shift
fi

dmenu_switches=""
if [[ -n $WAYLAND_DISPLAY ]]; then
	dmenu=fuzzel
	dmenu_switches=("--prompt" "$prompt" "--width" "80" "--dmenu")
	xdotool=("wtype" "--")
elif [[ -n $DISPLAY ]]; then
	dmenu=dmenu
	xdotool=("xdotool" "type" "--clearmodifiers" "--file" "-")
else
	echo "Error: No Wayland or X11 display detected" >&2
	exit 1
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | "$dmenu" "${dmenu_switches[@]}" "$@")

[[ -n $password ]] || exit

command='show'
if [[ $otp -ne 0 ]]; then
	command='otp'
fi

if [[ $copy -eq 0 ]]; then
	pass "$command" "$password" | { IFS= read -r pass; printf %s "$pass"; } | wtype -
else
	pass "$command" -c "$password" && wtype -d 200 -M ctrl v -m ctrl
fi
