#!/usr/bin/bash

# Taken and adapted from: https://git.zx2c4.com/password-store/tree/contrib/dmenu/passmenu

shopt -s nullglob globstar

cmd="show"
copy=""
prompt="Password: "
while [[ $# -gt 0 ]]; do
	case $1 in
	otp)
		cmd="otp"
		prompt="OTP: "
		shift
		;;
	copy)
		copy="--clip"
		shift
		;;
	*)
		break
		;;
	esac
done

dmenu_switches=()
if [[ -n $WAYLAND_DISPLAY ]]; then
	dmenu=fuzzel
	dmenu_switches=(--prompt "$prompt" --width 80 --dmenu)
	xdotool="wtype"
elif [[ -n $DISPLAY ]]; then
	dmenu=dmenu
	xdotool="xdotool type --clearmodifiers --file -"
else
	echo "Error: No Wayland or X11 display detected" >&2
	exit 1
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=("$prefix"/**/*.gpg)
password_files=("${password_files[@]#"$prefix"/}")
password_files=("${password_files[@]%.gpg}")

password=$(printf '%s\n' "${password_files[@]}" | "$dmenu" "${dmenu_switches[@]}" "$@")

[[ -n $password ]] || exit

pw=$(pass "$cmd" ${copy:+"$copy"} "$password" | {
	IFS= read -r pass
	printf %s "$pass"
})

if [[ -z $copy ]]; then
	"$xdotool" "$pw"
fi
